[package]
name = "test-worker"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
figment2 = "0.11"
figment2-cloudflare-workers = { path = ".." }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
worker = "0.7"
